
cursor {

no_hardware_cursors = true

}

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = QT_QPA_PLATFORMTHEME,qt6ct

opengl {
    nvidia_anti_flicker = false
}

debug {
    damage_tracking = 0
}

